spring.application.name=ProjetEncheres
spring.sql.init.mode=always
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=ENCHERES;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=kolixa
logging.level.org.springframework.jdbc.core=TRACE
server.servlet.session.timeout=5m
